# Generated by Django 5.2.8 on 2025-11-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='medicine_id',
            new_name='medicine',
        ),
    ]
