# Generated by Django 5.2.8 on 2025-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_medicine_id_orderitem_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('pdf', 'PDF Upload'), ('excel', 'Excel Upload')], default='manual', max_length=20),
        ),
    ]
